---
title: "Final Project Proposal"
author: 'Brandon Ly, Alejandro Cepeda, Brandon Dora, Benjamin Garcia'
date: 'April 10th, 2022'
output: html_document
---

---

# Proposals

The data set in which we are choosing revolves around the forest fires that 
happened in California from 2013 to 2020.

### Predicting Correlation Using SVM & LM

Portion done by: Brandon Ly

Brandon will be using both SVM and linear modeling in order to see if ML could 
predict if the fire were major or not using acres burned, and which season the 
fire took place in.

The purpose of his experiment is to see if the season (spring, winter, etc) has a 
correlation to the acres burned. So by using ML, if the models accurately 
predict if the fires were considered to be major using the seasons, it could 
possibly mean there is a correlation to be made.

Using RMSE, alike what we did in module 10, we could compare the RMSE of both the 
linear and support vector machine models to see which model were better, by 
doing so having multiple 'opinions' on the matter would be beneficial.

### Creating Density Maps to Visualize Occurences

Portion done by: Brandon Dora

This portion of the project will be centered around taking the dataset and 
creating multiple geographical representations of the data, that will not only 
provide a better look at the data itself, but will also allow the viewer to infer 
where these fires are more likely to occur.

Referring back to what was accomplished in module 4, using ggmap, along with a 
few other packages, we are able to visualize our data by geographically mapping 
where these fires occured, and to go even further, we will be creating density 
maps to show hotspots by the county the fires had taken place in.

### Building Shiny Web App for Interactive Visualization

Portion done by: Alejandro Cepeda

Alejandro will be focusing on an interactive plot using ggplot to allow the user 
to choose between the actual and the predicted results using Brandon Ly's model 
results. Alejandro's goal is to offer a visual representation of the predictions 
in order to determine the season with the highest correlation as well as to allow 
the end user to see the different levels of severity that each season can cause 
in terms of forest fire damage.

With the use of interactive visualization and the Shiny web app, which are topics 
covered in module 11, are the basis of this portion of the project. The ability to 
seamlessly view the variables of choice will allow our group to immediately 
display the insights and model results to the viewer during our presentation, as 
well as allow them to interact with the web app and analyze how each season affects 
the chances of a forest fire becoming major.

### Cleaning the Dataset

Portion done by: Benjamin Garcia

This portion will include downloading the fire dataset from kaggle and importing it into R.
Many of the columns in this dataset are not helpful or do not provide information which
we need. Additionally, the dataset is alphabetically ordered which may not be the
best format to have the columns in. The goal is to not only have a clean data frame,
but to be able to understand what the variable mean and if they are related.

Many of the data cleaning methods we have learned in this class and other
places are used such as removing columns, filling in na values and 
reordering columns so that it is easier to understand the entire
data set. It is in the plan to create a new column based on data from
other columns so that different operations and visualizations can be made.
The data cleaning will help make the visualizations more clear and highlight
what variables provide good information and which variables were either not as helpful
or provided no insight.

---

# Dataset

The data set our group will be working with can be found [here](https://www.kaggle.com/datasets/ananthu017/california-wildfire-incidents-20132020?select=California_Fire_Incidents.csv)

### Dataset Preview:
```{r message=FALSE, collapse=TRUE, paged.print=TRUE}
dataset <- read.csv("California_Fire_Incidents.csv")
head(dataset)
```

### Dataset Description
1636 observations, originally 40 variables, but after cleaning 28 variables.

Acres burned- acres of land burned

Active- t/f if active or inactive, 

Admin unit- an indicator of location by who is responding, reporting or responsible for the fire and/or its data collection
Most times if calfire is TRUE in CalFireIncident than it has calfire in admin unit

Airtanker- is a fixed-wing aircraft that can carry fire retardant or water and drop it on or in front of a fire to help slow the fire down. Number of airtankers?

Archive year- the year the fire occurred

calFireIncident- calfire is a specific organization in California that responds to fire incidents. 
Most likely bigger ones not small house fires that local firefighters respond to.

Canonical url - end of url specific for each fire

Condition statement- Description of specific conditions of that incident.

Control statement- similar to condition, control of fire situation.

County - county in California

County id- id of county

Crewsinvolved- numeric data of crew

Dozer-  Machine probably used to clean up or move things burned by the fire.

Engine- Fire engines, or pumpers, carry hose, tools, and pump water. The engine can also carry ladders, but they are set up by the fire fighters and can be carried 
around.  Key components of a fire engine include: Water tank (usually 500-750 gallons) Pump (approximately 1500 GPM) Complement of various types of hose (for both 
attack and supply).

Extinguished- extinguished date yyyy-mm-ddThh:mm:ssZ (seconds not recorded)

Fatalities- number of deaths

Featured- ? 

Final- ? 

Fuel type- type of fuel

Helicopter- number of helicopters

Injuries- number of injuries

Latitude

Location- better idea of where it occurs

Longitude

Majorincident- t/f if major incident

Name- name of fire

Percent contained - numerical value indicated the percent to which the fire is contained

Personnel- number of people

Public- public fire

Search description- description of search, words

Search keywords- keywords from previous variable

Started- start of the fire time yyyy-mm-ddThh:mm:ssZ 

Status- whether fire was finalized or not

Structures damaged- number

Structures destroyed- number

Structures evacuated- null

Structure threatened- number

Uniqueid- specific sequence of numbers and letters distinguishing each entry

Updated- date, update to the information about the fire yyyy-mm-ddThh:mm:ssZ

Water tenders- number of water tenders, A water tender is a type of firefighting apparatus that specialises in the transport of water from a water source to a fire 
scene. Water tenders are capable of drafting water from a stream, lake or hydrant.

